const sampleScript=`很多人做自媒体的时候，一开始都卡在一个地方：不知道自己到底要表达什么。

你看起来是在写文案，其实是在整理判断。你不是缺选题，你是还没有把那个最想说的观点压出来。

所以我建议你先别急着追热点，先问自己一句：这条内容看完以后，别人会记住哪一句话？

如果这句话不清楚，后面所有镜头、字幕、音乐都会变成装饰。它们看起来很热闹，但没有方向。

真正有效的口播，是先让人点头，再让人停下来想一下，最后给他一个可以马上行动的小方法。`;
const lex={发现:["发现","未知","概念","有用","原来","学到"],好奇:["好奇","疑惑","为什么","到底","什么"],警觉:["恐惧","害怕","担心","风险","不安"],共鸣:["很多人","你","其实","不是","卡在","缺","痛点"],判断:["我建议","我认为","所以","真正","判断","清楚","方向"],推进:["先","再","最后","开始","行动","方法"],强调:["一定","最","必须","关键","记住","停下来"],孤独:["孤独","一个人","空","没人","夜","房间","便利店"]};
const style={发现:["#177f7a","发现感"],好奇:["#306ba8","带着疑问"],警觉:["#8f4a3d","压住不安"],共鸣:["#59616b","贴近感"],判断:["#156f64","下判断"],推进:["#b6781b","给步骤"],强调:["#c9493f","重音"],孤独:["#3f6f9f","留空"]};
const $=s=>document.querySelector(s);const els={input:$('#scriptInput'),count:$('#wordCounter'),status:$('#analysisStatus'),pulse:$('#creativePulse'),map:$('#visualMap'),cuts:$('#cutList'),goals:$('#goalStrip'),emotion:$('#emotionList'),breath:$('#breathList'),peaks:$('#emotionPeakList'),shots:$('#shotList'),title:$('#activeShotTitle'),note:$('#activeShotNote'),detailEmotion:$('#detailEmotion'),detailLens:$('#detailLens'),detailTone:$('#detailTone'),detailBreath:$('#detailBreath'),detailCut:$('#detailCut'),detailSubtitle:$('#detailSubtitle'),rewrite:$('#rewriteAdvice'),rail:$('#rhythmRail'),frameLabel:$('#frameLabel'),frameSubtitle:$('#frameSubtitle'),frameAroll:$('#frameAroll'),frameLocation:$('#frameLocation'),frameBroll:$('#frameBroll'),frameEmotionBuild:$('#frameEmotionBuild'),format:$('#formatSelect'),duration:$('#durationSelect'),visualStyle:$('#styleSelect')};
let analysis=null,active=0;
function split(t){return t.split(/\n+|(?<=[。！？!?])/).map(x=>x.trim()).filter(Boolean)}
function emotion(seg){let scores=Object.fromEntries(Object.keys(lex).map(k=>[k,0]));for(const [k,ws] of Object.entries(lex))for(const w of ws)if(seg.includes(w))scores[k]+=w.length>2?2:1;let top=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0];let e=top[1]?top[0]:seg.includes('？')?'好奇':seg.includes('所以')?'判断':'共鸣';let n=Math.min(96,30+seg.length*1.2+top[1]*12);return{e,force:n>82?'强烈':n>68?'明显':n>52?'稳定':'轻微',score:n}}
function role(s,e,i,total){if(i===0)return e==='发现'?'开场发现':e==='好奇'?'开场未知':e==='警觉'?'开场风险':'开场铺垫';if(i===total-1)return'收束';if(e==='判断')return'观点变清楚';if(e==='推进')return'推进';if(e==='孤独'||e==='警觉')return'下沉';return'过渡'}
function curve(s,e,i,total){let p=total<=1?0:i/(total-1),v=i===0?76:p>.8?72:48;if(e==='判断'||e==='发现'||e==='强调')v+=22;if(e==='孤独'||e==='警觉'||/不清楚|卡住|风险/.test(s))v-=20;if(e==='推进')v+=12;return Math.max(24,Math.min(92,Math.round(v)))}
function shot(seg,i,total){let m=emotion(seg),r=role(seg,m.e,i,total),c=curve(seg,m.e,i,total);let decision=i===0||m.e==='判断'||m.e==='推进'?'主线':seg.length>58?'待讨论':c<42?'旁支':'过渡';return{id:i+1,text:seg,emotion:m.e,force:m.force,score:m.score,curve:c,role:r,decision,color:style[m.e][0],tone:style[m.e][1],breath:i===0?.3:m.e==='强调'?.5:.25,lens:m.e==='孤独'?'85mm Zeiss':i%3===0?'35mm Zeiss':i%3===1?'50mm Zeiss':'35mm Cooke',subtitle:(seg.match(/有用|发现|未知|恐惧|不是|所以|真正|为什么|问题|判断|行动/)||['压成一句短字幕'])[0],aroll:`A-roll 主讲：${r.includes('开场')?'让说话的人成立，不急着证明结构。':m.e==='判断'?'完整说判断句，不让素材抢走表达。':'主讲不断线，素材只做补充。'}`,location:m.e==='孤独'?'夜窗、便利店门口、空走廊':m.e==='发现'?'桌面书页、屏幕、手写笔记':'干净自拍机位或日常工作台',broll:m.e==='推进'?'步骤清单、屏幕录制、手写关键词':m.e==='判断'?'少用 B-roll，保留主讲可信度':'关键词、环境空镜或资料细节',build:c>76?'语气往上推，但保留真实停顿。':c<42?'压低表达，留空和环境声。':'保持主讲稳定，给下一段过渡。',rewrite:m.e==='发现'?'不要只说开心，要说你意识到什么以及为什么有用。':'把导演意图说清楚，再决定素材是否需要。'}}
function smooth(ps){if(ps.length<2)return'';let d=`M ${ps[0].x} ${ps[0].y}`;for(let i=0;i<ps.length-1;i++){let p0=ps[i-1]||ps[i],p1=ps[i],p2=ps[i+1],p3=ps[i+2]||p2;d+=` C ${(p1.x+(p2.x-p0.x)/6).toFixed(2)} ${(p1.y+(p2.y-p0.y)/6).toFixed(2)}, ${(p2.x-(p3.x-p1.x)/6).toFixed(2)} ${(p2.y-(p3.y-p1.y)/6).toFixed(2)}, ${p2.x} ${p2.y}`}return d}
function quality(shots){let all=shots.map(s=>s.text).join('');let items=[['真实观察',/我|你|很多人|其实|发现|想到|意识到/.test(all),'像是从真实经验里说出来'],['具体处境',/城市|房间|便利店|地铁|桌面|手机|屏幕|工作|夜|门|窗/.test(all),'有可拍的生活场景'],['诚实判断',/不是|其实|我认为|我建议|真正|所以|判断|清楚|有用|问题/.test(all),'有自己的看法'],['个人声音',/我|你|我们|她|他/.test(all),'有人在说话']];let miss=items.filter(x=>!x[1]).map(x=>x[0]);return{items,sentence:miss.length?`还需要讨论 ${miss.join('、')}，否则会像观点摘要。`:'它成立在内容：有观察、有处境、有判断，也有说话者声音。'}}
function analyze(){let segs=split(els.input.value);let shots=segs.map((s,i)=>shot(s,i,segs.length));let weights={};for(const s of shots)weights[s.emotion]=(weights[s.emotion]||0)+s.score+(s.decision==='主线'?20:0);let core=Object.entries(weights).sort((a,b)=>b[1]-a[1])[0]?.[0]||'共鸣';let peak=[...shots].sort((a,b)=>b.score-a.score)[0]||shots[0];let pivot=shots.find(s=>s.emotion==='判断'||s.emotion==='推进')||peak||shots[0];let q=quality(shots);analysis={shots,core,peak,pivot,q};render()}
function render(){if(!analysis)return;document.body.classList.add('analysis-ready');els.status.textContent=`${analysis.shots.length} 个段落`;els.status.classList.add('ready');let first=analysis.shots[0],op=`这版可以先围绕“${analysis.core}”去试拍，但它只是导演意图假设，不是最终判决。`;els.pulse.innerHTML=`<article class="pulse-hero" style="--c:${first.color}"><span>进入方式</span><strong>${first.emotion} · ${first.role}</strong><p>${first.text}</p></article><div class="pulse-side"><div class="pulse-strip"><button class="pulse-item" style="--c:${first.color}"><span>Entry</span><strong>P${first.id} ${first.emotion}</strong><em>${first.tone}</em></button><button class="pulse-item" style="--c:${analysis.pivot.color}"><span>Turn</span><strong>P${analysis.pivot.id} ${analysis.pivot.emotion}</strong><em>${analysis.pivot.role}</em></button><button class="pulse-item" style="--c:${analysis.peak.color}"><span>Peak</span><strong>P${analysis.peak.id} ${analysis.peak.force}</strong><em>${analysis.peak.build}</em></button></div><article class="opinion-card" style="--c:${first.color};--opinion-color:${first.color}"><span>导演意图假设</span><strong>先围绕“${analysis.core}”试拍</strong><p>${op}</p><p>${analysis.q.sentence}</p><div class="quality-list">${analysis.q.items.map(i=>`<b class="${i[1]?'ok':'warn'}">${i[0]} · ${i[2]}</b>`).join('')}</div><div class="question-list"><em>导演真正想让观众带走的是情绪，还是情绪背后的观点？</em><em>旁支段落是不是风格的一部分，而不是需要被拿掉的内容？</em></div></article></div>`;renderMap();renderLists();setActive(0)}
function renderMap(){let ps=analysis.shots.map((s,i)=>({x:8+(i/(analysis.shots.length-1||1))*84,y:88-s.curve*.72,s}));let d=smooth(ps);els.map.innerHTML=`<div class="map-stage"><svg class="map-line" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="${d}" fill="none" stroke="rgba(23,25,31,.16)" stroke-width="9" stroke-linecap="round"/><path d="${d}" fill="none" stroke="#17191f" stroke-width="2.2" stroke-linecap="round"/></svg><svg class="map-hit-layer" viewBox="0 0 100 100" preserveAspectRatio="none">${ps.map(p=>`<g class="svg-node" style="--node-color:${p.s.color}"><circle cx="${p.x}" cy="${p.y}" r="3"/><text x="${p.x}" y="${p.y+1}" text-anchor="middle">P${p.s.id}</text></g>`).join('')}</svg>${ps.map((p,i)=>`<button class="map-node" data-i="${i}" style="--x:${p.x}%;--y:${p.y}%;--node-color:${p.s.color}">P${p.s.id}</button>`).join('')}<div class="active-curve-note" style="--c:${analysis.shots[active]?.color||'#156f64'}"><span>P${analysis.shots[active]?.id||1} · ${analysis.shots[active]?.role||''}</span><strong>${analysis.shots[active]?.emotion||''} · ${analysis.shots[active]?.force||''}</strong><p>${analysis.shots[active]?.build||''}</p></div><div class="timeline-ticks">${analysis.shots.map(s=>`<span>P${s.id}</span>`).join('')}</div></div>`;document.querySelectorAll('.map-node').forEach(b=>b.onclick=()=>setActive(+b.dataset.i))}
function renderLists(){els.cuts.innerHTML=analysis.shots.filter(s=>s.decision!=='主线').slice(0,3).map(s=>`<button class="cut-card" style="--c:${s.color}" onclick="setActive(${s.id-1})"><span>${s.decision} · P${s.id}</span><strong>${s.role}</strong><p>${s.text}</p></button>`).join('')||`<article class="cut-card keep"><span>讨论状态</span><strong>这版可以进入试拍讨论</strong><p>先看导演意图，不急着判定好坏。</p></article>`;els.goals.innerHTML=['内容可信','视觉可拍','情绪清晰','讨论空间'].map(x=>`<article class="goal-card"><span>${x}</span><strong>可讨论</strong></article>`).join('');let sum={};for(const s of analysis.shots)sum[s.emotion]=(sum[s.emotion]||0)+1;els.emotion.innerHTML=Object.entries(sum).map(([k,v])=>`<article class="insight-card"><strong>${k}</strong><p>${v} 个段落触发。用于讨论导演意图，不作为评分。</p></article>`).join('');els.breath.innerHTML=analysis.shots.map(s=>`<article class="insight-card"><strong>P${s.id} · ${s.breath.toFixed(2)}s</strong><p>${s.build}</p></article>`).join('');els.peaks.innerHTML=analysis.shots.slice(0,4).map(s=>`<button class="emotion-peak" onclick="setActive(${s.id-1})" style="--peak-color:${s.color};--peak-level:${s.score}%"><span class="peak-index">P${s.id}</span><span class="peak-main"><strong>${s.emotion} · ${s.force}</strong><em>${s.role}</em><i>${s.text}</i></span><span class="peak-meter"><b></b></span></button>`).join('');els.shots.innerHTML=analysis.shots.map((s,i)=>`<article class="shot-card" onclick="setActive(${i})"><span class="shot-number">${String(s.id).padStart(2,'0')}</span><span><strong>P${s.id} · ${s.role}</strong><p>${s.text}</p><span class="shot-meta"><span class="chip">${s.emotion}</span><span class="chip">${s.decision}</span><span class="chip">${s.lens}</span></span></span></article>`).join('')}
function setActive(i){active=i;let s=analysis.shots[i];document.querySelectorAll('.shot-card').forEach((c,n)=>c.classList.toggle('active',n===i));els.title.textContent=`P${s.id} · ${s.role}`;els.note.textContent=s.text;els.detailEmotion.textContent=`${s.emotion} · ${s.force}`;els.detailLens.textContent=s.lens;els.detailTone.textContent=s.tone;els.detailBreath.textContent=`${s.breath.toFixed(2)}s`;els.detailCut.textContent=s.decision;els.detailSubtitle.textContent=s.subtitle;els.rewrite.textContent=s.rewrite;els.frameLabel.textContent=`P${s.id} · ${s.role}`;els.frameSubtitle.textContent=s.subtitle;els.frameAroll.textContent=s.aroll;els.frameLocation.textContent=s.location;els.frameBroll.textContent=s.broll;els.frameEmotionBuild.textContent=s.build;els.rail.innerHTML=analysis.shots.map((x,n)=>`<button class="rhythm-node ${n===i?'active':''}" onclick="setActive(${n})" style="--node-color:${x.color};--s:${Math.max(30,x.curve/1.7)}px"><span>P${x.id}</span></button>`).join('');renderMap()}
function updateCount(){els.count.textContent=`${els.input.value.replace(/\s/g,'').length} 字`}function exportMd(){if(!analysis)return;let md=['# Script Emotion Workbench Export','',`导演意图假设：先围绕“${analysis.core}”试拍。`,analysis.q.sentence,'',...analysis.shots.map(s=>`## P${s.id} ${s.emotion}\n- 文稿：${s.text}\n- 讨论状态：${s.decision}\n- A-roll：${s.aroll}\n- 自拍/外景点：${s.location}\n- B-roll：${s.broll}\n- 情绪铺法：${s.build}`)];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([md.join('\n')],{type:'text/markdown'}));a.download='script-emotion-workbench.md';a.click()}
els.input.oninput=updateCount;$('#loadSample').onclick=()=>{els.input.value=sampleScript;updateCount();analyze()};$('#analyzeBtn').onclick=analyze;$('#exportMarkdown').onclick=exportMd;updateCount();
